A man who dares to waste one hour of time has not discovered the value of life. -- Charles Darwin

diff --git a/2f49d1e094c14e7888828fc0911d6a8f b/2f49d1e094c14e7888828fc0911d6a8f
--- a/2f49d1e094c14e7888828fc0911d6a8f
+++ b/2f49d1e094c14e7888828fc0911d6a8f
@@ -1,68 +1,37 @@
-Wed Oct 25 19:42:31 JST 2017
-#!/usr/bin/env python3
-# ----------------------------------------------------------------------
-# BBox-Label-Tool
-#1
-#231 204 403 455
-# ----------------------------------------------------------------------
-# darknet 
-#0 0.49531250000000004 0.6864583333333333 0.26875 0.5229166666666667
-# ----------------------------------------------------------------------
-import glob
+Sun Nov 12 19:48:57 JST 2017
+#!/bin/sh
+#
+# An example hook script to prepare the commit log message.
+# Called by "git commit" with the name of the file that has the
+# commit message, followed by the description of the commit
+# message's source.  The hook's purpose is to edit the commit
+# message file.  If the hook fails with a non-zero status,
+# the commit is aborted.
+#
+# To enable this hook, rename this file to "prepare-commit-msg".
 
-def convert(size, box):
-    dw = (size[0])
-    dh = (size[1])
-    x = (box[0] + box[2])/2.0
-    y = (box[1] + box[3])/2.0
-    w = box[2] - box[0]
-    h = box[3] - box[1]
-    x = x/dw
-    w = w/dw
-    y = y/dh
-    h = h/dh
-    return (x,y,w,h)
+# This hook includes three examples.  The first comments out the
+# "Conflicts:" part of a merge commit.
+#
+# The second includes the output of "git diff --name-status -r"
+# into the message, just before the "git status" output.  It is
+# commented because it doesn't cope with --amend or with squashed
+# commits.
+#
+# The third example adds a Signed-off-by line to the message, that can
+# still be edited.  This is rarely a good idea.
 
+case "$2,$3" in
+  merge,)
+    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
 
-def _convert(size, box):
-    dw = 1./(size[0])
-    dh = 1./(size[1])
-    x = (box[0] + box[2])/2.0 - 1
-    y = (box[1] + box[3])/2.0 - 1
-    w = box[2] - box[0]
-    h = box[3] - box[1]
-    x = x*dw
-    w = w*dw
-    y = y*dh
-    h = h*dh
-    return (x,y,w,h)
+# ,|template,)
+#   /usr/bin/perl -i.bak -pe '
+#      print "\n" . `git diff --cached --name-status -r`
+#	 if /^#/ && $first++ == 0' "$1" ;;
 
-flist = glob.glob("../data4bbox/Labels/777/image*.txt")
-flist.sort()
+  *) ;;
+esac
 
-for fname in flist:
-    with open(fname, "r") as fd:
-        lines = fd.readlines()
-        l = lines[1].replace('\n','')
-        box_str = l.split(' ')
-        box = []
-        for v in box_str:
-            box.append(float(int(v)))
-
-        size = [640.0, 480.0]
-        x, y, w, h = convert(size, box)
-
-        if False:
-        #if True:
-            x0 = box[0]
-            y0 = box[1]
-            x1 = box[2]
-            y1 = box[3]
-            x = (x0 + x1)/2.0/size[0]
-            y = (y0 + y1)/2.0/size[1]
-
-
-        #print(fname, lines[1], box, x, y, w, h)
-        print("%1.17f %1.17f %1.17f %1.17f " %(x, y, w, h))
-
-    
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
