There are two tragedies in life. One is not to get your heart's desire. The other is to get it. -- George Bernard Shaw

diff --git a/63775ad95d744923a271ae0bb26e096d b/63775ad95d744923a271ae0bb26e096d
--- a/63775ad95d744923a271ae0bb26e096d
+++ b/63775ad95d744923a271ae0bb26e096d
@@ -1,129 +1,170 @@
-Sun Feb 27 19:43:58 JST 2011
-#!/usr/bin/env python3
-# -*- coding: utf-8 -*-
-import argparse
-import numpy as np
-import cv2
-from datetime import datetime
-import mkdir
-import aieye_find
-import time
-import sys
+Sat Mar  5 19:37:03 JST 2011
+#!/bin/sh
+#
+# Copyright (c) 2006, 2008 Junio C Hamano
+#
+# The "pre-rebase" hook is run just before "git rebase" starts doing
+# its job, and can prevent the command from running by exiting with
+# non-zero status.
+#
+# The hook is called with the following parameters:
+#
+# $1 -- the upstream the series was forked from.
+# $2 -- the branch being rebased (or empty when rebasing the current branch).
+#
+# This sample shows how to prevent topic branches that are already
+# merged to 'next' branch from getting rebased, because allowing it
+# would result in rebasing already published history.
 
-class_num = 1 # annotate number for class: 001: hamada
-drawing = False
-posi0 = [-1,-1]
-posi1 = [-1,-1]
-image_size = [-1, -1] # [height, width]
+publish=next
+basebranch="$1"
+if test "$#" = 2
+then
+	topic="refs/heads/$2"
+else
+	topic=`git symbolic-ref HEAD` ||
+	exit 0 ;# we do not interrupt rebasing detached HEAD
+fi
 
-def mouse_event(event,x,y,flags,param):
-    global posi0, posi1, drawing
+case "$topic" in
+refs/heads/??/*)
+	;;
+*)
+	exit 0 ;# we do not interrupt others.
+	;;
+esac
 
-    if x < 0: x = 0 
-    if y < 0: y = 0 
-    if x >= image_size[1]: x = image_size[1] - 1
-    if y >= image_size[0]: y = image_size[0] - 1
+# Now we are dealing with a topic branch being rebased
+# on top of master.  Is it OK to rebase it?
+
+# Does the topic really exist?
+git show-ref -q "$topic" || {
+	echo >&2 "No such branch $topic"
+	exit 1
+}
+
+# Is topic fully merged to master?
+not_in_master=`git rev-list --pretty=oneline ^master "$topic"`
+if test -z "$not_in_master"
+then
+	echo >&2 "$topic is fully merged to master; better remove it."
+	exit 1 ;# we could allow it, but there is no point.
+fi
+
+# Is topic ever merged to next?  If so you should not be rebasing it.
+only_next_1=`git rev-list ^master "^$topic" ${publish} | sort`
+only_next_2=`git rev-list ^master           ${publish} | sort`
+if test "$only_next_1" = "$only_next_2"
+then
+	not_in_topic=`git rev-list "^$topic" master`
+	if test -z "$not_in_topic"
+	then
+		echo >&2 "$topic is already up-to-date with master"
+		exit 1 ;# we could allow it, but there is no point.
+	else
+		exit 0
+	fi
+else
+	not_in_next=`git rev-list --pretty=oneline ^${publish} "$topic"`
+	/usr/bin/perl -e '
+		my $topic = $ARGV[0];
+		my $msg = "* $topic has commits already merged to public branch:\n";
+		my (%not_in_next) = map {
+			/^([0-9a-f]+) /;
+			($1 => 1);
+		} split(/\n/, $ARGV[1]);
+		for my $elem (map {
+				/^([0-9a-f]+) (.*)$/;
+				[$1 => $2];
+			} split(/\n/, $ARGV[2])) {
+			if (!exists $not_in_next{$elem->[0]}) {
+				if ($msg) {
+					print STDERR $msg;
+					undef $msg;
+				}
+				print STDERR " $elem->[1]\n";
+			}
+		}
+	' "$topic" "$not_in_next" "$not_in_master"
+	exit 1
+fi
+
+exit 0
+
+################################################################
+
+This sample hook safeguards topic branches that have been
+published from being rewound.
+
+The workflow assumed here is:
+
+ * Once a topic branch forks from "master", "master" is never
+   merged into it again (either directly or indirectly).
+
+ * Once a topic branch is fully cooked and merged into "master",
+   it is deleted.  If you need to build on top of it to correct
+   earlier mistakes, a new topic branch is created by forking at
+   the tip of the "master".  This is not strictly necessary, but
+   it makes it easier to keep your history simple.
+
+ * Whenever you need to test or publish your changes to topic
+   branches, merge them into "next" branch.
+
+The script, being an example, hardcodes the publish branch name
+to be "next", but it is trivial to make it configurable via
+$GIT_DIR/config mechanism.
+
+With this workflow, you would want to know:
+
+(1) ... if a topic branch has ever been merged to "next".  Young
+    topic branches can have stupid mistakes you would rather
+    clean up before publishing, and things that have not been
+    merged into other branches can be easily rebased without
+    affecting other people.  But once it is published, you would
+    not want to rewind it.
+
+(2) ... if a topic branch has been fully merged to "master".
+    Then you can delete it.  More importantly, you should not
+    build on top of it -- other people may already want to
+    change things related to the topic as patches against your
+    "master", so if you need further changes, it is better to
+    fork the topic (perhaps with the same name) afresh from the
+    tip of "master".
+
+Let's look at this example:
+
+		   o---o---o---o---o---o---o---o---o---o "next"
+		  /       /           /           /
+		 /   a---a---b A     /           /
+		/   /               /           /
+	       /   /   c---c---c---c B         /
+	      /   /   /             \         /
+	     /   /   /   b---b C     \       /
+	    /   /   /   /             \     /
+    ---o---o---o---o---o---o---o---o---o---o---o "master"
 
 
-    if event == cv2.EVENT_LBUTTONDOWN:
-        print ('Push')
-        drawing = True
-        posi0[0] = x
-        posi0[1] = y
+A, B and C are topic branches.
 
+ * A has one fix since it was merged up to "next".
 
-    elif event == cv2.EVENT_MOUSEMOVE:
-        if drawing == True:
-            print ("Drawing... (%d, %d)" % (x, y))
-        else:
-            pass
-    elif event == cv2.EVENT_LBUTTONUP:
-        print ('Up')
-        drawing = False
-        cv2.rectangle(image, (posi0[0],posi0[1]), (x,y), (0,255,0), 1)
-        posi1[0] = x
-        posi1[1] = y
+ * B has finished.  It has been fully merged up to "master" and "next",
+   and is ready to be deleted.
 
-def save_data(image_dbg, image_orig, fnum):
-    global class_num, posi0, posi1
-    basedir = '../data4bbox/'
-    fname_body = "image_%04d" % fnum
+ * C has not merged to "next" at all.
 
-    # save image_orig (for Images/)
-    fname = fname_body + ".jpg"
-    basedir_images = basedir+"Images/%03d/"%(class_num)
-    ofname_images = mkdir.get_filename_frame_simple(basedir_images , fname)
-    print (ofname_images)
-    cv2.imwrite(ofname_images, image_orig)
+We would want to allow C to be rebased, refuse A, and encourage
+B to be deleted.
 
-    # save image_dbg (for Debug/)
-    fname = fname_body + ".jpg"
-    basedir_dbg = basedir+"Debug/%03d/"%(class_num)
-    ofname_dbg  = mkdir.get_filename_frame_simple(basedir_dbg , fname)
-    print (ofname_dbg)
-    cv2.imwrite(ofname_dbg, image_dbg)
+To compute (1):
 
-    # save labes
-    fname = fname_body + ".txt"
-    basedir_labels = basedir+"Labels/%03d/"%(class_num)
-    ofname_labels  = mkdir.get_filename_frame_simple(basedir_labels , fname)
-    print (ofname_labels)
-    bbox_posi = []
-    bbox_posi.append(min(posi0[0], posi1[0]))
-    bbox_posi.append(min(posi0[1], posi1[1]))
-    bbox_posi.append(max(posi0[0], posi1[0]))
-    bbox_posi.append(max(posi0[1], posi1[1]))
-    with open(ofname_labels, "w") as file:
-        file.write("1\n")
-        file.write("%d %d %d %d\n" % (tuple(bbox_posi)))
+	git rev-list ^master ^topic next
+	git rev-list ^master        next
 
-if '__main__' == __name__:
-    basedir = '../log/'
-    if (len(sys.argv) > 1 ):
-        basedir = sys.argv[1]
-    
-    iflist = [] 
-    for fname in aieye_find.find(basedir, '*.jpg'):
-        iflist.append(fname)
+	if these match, topic has not merged in next at all.
 
-    iflist.sort()
-    ni = len(iflist)
-    i = 0
+To compute (2):
 
-    #    for i, fname in enumerate(iflist):
-    while( i < ni) :
-        fname = iflist[i]
-        print (fname, "%d/%d (%1.3f)"%(i, ni, i/ni))
+	git rev-list master..topic
 
-        image_orig = cv2.imread(fname, cv2.IMREAD_COLOR)
-        image = image_orig.copy()
-        image_size[0], image_size[1] = image.shape[:2]
-        is_next = False
-        while (not is_next):
-            cv2.imshow("THBox-annon.py", image)
-            cv2.namedWindow("THBox-annon.py", cv2.WINDOW_NORMAL)
-            cv2.setMouseCallback("THBox-annon.py", mouse_event)
-            key = cv2.waitKey(1) & 0xFF
-            if key == ord(' '):
-                save_data(image, image_orig, i)
-                is_next = True
-            if key  == 83:  # ->
-                is_next = True
-            if key  == 81:  # <-
-                i = i - 2
-                is_next = True
-            if key == ord('r'): # Reset
-                i = i - 1
-                is_next = True
-            if key  == ord('q'): 
-                i = ni
-                break
-        i = i+1
-
-    cv2.destroyAllWindows()
-
-
-
-
-
-    
+	if this is empty, it is fully merged to "master".
