I do not seek, I find. -- Pablo Picasso

diff --git a/6caca47ecb444e81985d7bd3d8f73005 b/6caca47ecb444e81985d7bd3d8f73005
--- a/6caca47ecb444e81985d7bd3d8f73005
+++ b/6caca47ecb444e81985d7bd3d8f73005
@@ -1,5 +1,25 @@
-Mon Apr 12 19:49:33 JST 2021
--- ProjNav VHDL simulation template: sim_pfpga_dma.udo
--- You may edit this file after the line that starts with
--- '-- START' to customize your simulation
--- START user-defined simulation commands
+Thu Apr 15 19:46:43 JST 2021
+#!/bin/sh
+#
+# An example hook script to check the commit log message.
+# Called by "git commit" with one argument, the name of the file
+# that has the commit message.  The hook should exit with non-zero
+# status after issuing an appropriate message if it wants to stop the
+# commit.  The hook is allowed to edit the commit message file.
+#
+# To enable this hook, rename this file to "commit-msg".
+
+# Uncomment the below to add a Signed-off-by line to the message.
+# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
+# hook is more suited to it.
+#
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
+
+# This example catches duplicate Signed-off-by lines.
+
+test "" = "$(grep '^Signed-off-by: ' "$1" |
+	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
+	echo >&2 Duplicate Signed-off-by lines.
+	exit 1
+}
