I have nothing to offer but blood, toil, tears, and sweat. -- Winston Churchill

diff --git a/b4a0185fe94a4148aed79d957d0ee08d b/b4a0185fe94a4148aed79d957d0ee08d
--- a/b4a0185fe94a4148aed79d957d0ee08d
+++ b/b4a0185fe94a4148aed79d957d0ee08d
@@ -1,51 +1,51 @@
-Tue May 20 19:34:15 JST 2014
--- Copyright 2004 Tsuyoshi Hamada
---
---
---clk         __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __~~ __
---[dma_we]    _______/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\______________
---state_dmaw          0  >< 1 >< 2                                    >< 3 >< 0 
+Wed Jun  4 19:33:40 JST 2014
+#!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
--- 0->1 : if((state==0)&&(dma_we==1))
--- 1->2 : if (state==1)
--- 2->3 : if((state==2) &&(dma_we==0))
--- 3->0 : if (state==3)
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+	against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
 
-library IEEE;
-use IEEE.STD_LOGIC_1164.ALL;
-use IEEE.STD_LOGIC_UNSIGNED.ALL;
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
-entity dmaw_state is
-  port (
-    RST      : in std_logic;
-    CLK      : in std_logic;
-    ENABLE   : in std_logic;
-    STATE    : out std_logic_vector(1 downto 0) );
-end dmaw_state;
+# Redirect output to stderr.
+exec 1>&2
 
-architecture rtl of dmaw_state is
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
+fi
 
-signal state_ff : std_logic_vector(1 downto 0);
-begin
-
-  STATE <= state_ff;
-
-  process (RST,CLK,ENABLE,state_ff) begin
-    if(RST='1') then
-      state_ff <= (others=>'0');
-    elsif(CLK'event and CLK = '1') then
-      if((state_ff="00") AND (ENABLE='1')) then
-        state_ff <= "01";
-      elsif(state_ff = "01") then
-        state_ff <= "10";
-      elsif((state_ff = "10") AND (ENABLE='0')) then
-        state_ff <= "11";
-      elsif((state_ff = "10") AND (ENABLE='1')) then
-        state_ff <= "10";
-      else -- if(state_ff = "11") then
-        state_ff <= "00";
-      end if;
-    end if;
-  end process;
-
-end rtl;
+# If there are whitespace errors, print the offending file names and fail.
+exec git diff-index --check --cached $against --
